# Generated by Django 2.2.6 on 2019-10-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20181029_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appform1',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='accn',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='accno',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='brno',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='category',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='ifs',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='quo',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='result',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='year',
        ),
    ]
