# Generated by Django 2.2.6 on 2019-10-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20191027_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appform1',
            name='add1',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='add2',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='city',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='country',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='appform1',
            name='state',
        ),
    ]
